name: Crystal spec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: crystal spec
    - name: Build docs
      run: crystal docs
    - name: deploy docs
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: oprypin/push-to-gh-pages@v3
      with:
        publish_dir: ./docs
